const List<String> motivationalQuotes = [
  "You don’t get what you wish for, you get what you work for.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your comfort zone is costing you your future.",
  "Motivation fades. Systems don’t.",
  "You either suffer the pain of discipline or the pain of regret.",
  "If it were easy, everyone would do it.",
  "Small daily improvements lead to massive results.",
  "Excuses make today easy but tomorrow hard.",
  "Hard work beats talent when talent doesn’t work hard.",
  "You can’t cheat the grind—it knows how much you’ve invested.",
  "Your mind is your biggest weapon—or your biggest enemy.",
  "Growth begins when you start doing things you’re bad at.",
  "Stop waiting to feel ready.",
  "Fear is just growth in disguise.",
  "You become what you repeatedly do.",
  "Doubt kills more dreams than failure ever will.",
  "Your future is created by what you do today, not tomorrow.",
  "Be addicted to improving yourself.",
  "If you don’t control your mind, someone else will.",
  "Every master was once a beginner who refused to quit.",
  "The struggle you’re in today is building the strength you need tomorrow.",
  "Pain is temporary. Regret lasts forever.",
  "Nobody sees the nights you cried, only the success you show.",
  "You’re not behind—you’re just being prepared.",
  "Your darkest moments often lead to your greatest breakthroughs.",
  "What hurts you teaches you.",
  "Rock bottom is a solid foundation to rebuild your life.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Sometimes you have to break to rebuild better.",
  "Struggle is the price of greatness.",
  "Dreams don’t work unless you do.",
  "Success is built on consistency, not intensity.",
  "Start where you are. Use what you have. Do what you can.",
  "Action cures fear.",
  "Don’t watch the clock—do what it does. Keep going.",
  "You don’t need more time, you need more focus.",
  "Stop overthinking and start doing.",
  "Opportunities don’t happen, you create them.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Winners focus on winning. Losers focus on winners.",
  "You owe it to yourself to become everything you dreamed of.",
  "Don’t downgrade your dream to fit your reality—upgrade your mindset.",
  "You are stronger than your excuses.",
  "Act like the person you want to become.",
  "Confidence comes from keeping promises to yourself.",
  "No one is coming to save you—be your own hero.",
  "You didn’t come this far to only come this far.",
  "Your only competition is who you were yesterday.",
  "Stop doubting yourself. You’ve survived 100% of your worst days.",
  "The life you want is on the other side of discipline.",
  "If your not sure, thats your answer"
];
